name: upload artifacts
on:
    push:
    workflow_dispatch:
env:
    emp_name: shinoj
jobs:
           
    upload_artifact:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repository
          uses: actions/checkout@v6
        - name: install cowsay
          run: |
            sudo apt update
            sudo  apt install -y cowsay
        - name: create dragon
          run: cowsay -f dragon "DevOps rocks" > dragon.txt
        - name: greets
          run: echo "welcome to devops ${{env.emp_name}}"
        - name: upload dragon file
          uses: actions/upload-artifact@v4
          with:
            name: dragon
            path: dragon.txt
